
name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Build APK using flet and briefcase
      run: |
        pip install briefcase
        briefcase create android
        briefcase build android
        briefcase package android

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: ./build/android/*.apk
